u-boot: Add opensbi do_deploy dep only for machines with opensbi
This is a generic bbappend and opensbi is riscv specific, so this causes
problems when this layer is includes and a build is done for non-riscv
machines e.g.

MACHINE=qemumips bitbake -n world

will show the problem

ERROR: Nothing PROVIDES 'opensbi'
opensbi was skipped: incompatible with host mips-yoe-linux-musl (not in COMPATIBLE_HOST)
NOTE: Runtime target 'u-boot-default-env' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['u-boot-default-env', 'opensbi']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'libubootenv', 'u-boot-default-env', 'opensbi']

Signed-off-by: Khem Raj <raj.khem@gmail.com>